"""
This type stub file was generated by pyright.
"""

class Bit:
    def __init__(self, value) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def to_list(self): # -> list[Any]:
        ...
    
    def to_numpy(self): # -> ndarray[tuple[int], dtype[Any]]:
        ...
    
    def to_text(self): # -> str:
        ...
    
    def to_binary(self): # -> bytes:
        ...
    
    @classmethod
    def from_text(cls, value): # -> Self:
        ...
    
    @classmethod
    def from_binary(cls, value): # -> Self:
        ...
    


