"""
This type stub file was generated by pyright.
"""

class HalfVector:
    def __init__(self, value) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def dimensions(self): # -> int:
        ...
    
    def to_list(self): # -> Any:
        ...
    
    def to_numpy(self): # -> NDArray[Any] | ndarray[Any, Any]:
        ...
    
    def to_text(self): # -> str:
        ...
    
    def to_binary(self): # -> bytes:
        ...
    
    @classmethod
    def from_text(cls, value): # -> Self:
        ...
    
    @classmethod
    def from_binary(cls, value): # -> Self:
        ...
    


