"""
This type stub file was generated by pyright.
"""

NO_DEFAULT = ...
class SparseVector:
    def __init__(self, value, dimensions=..., /) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def dimensions(self): # -> int:
        ...
    
    def indices(self): # -> list[int]:
        ...
    
    def values(self): # -> list[float]:
        ...
    
    def to_coo(self):
        ...
    
    def to_list(self): # -> list[float]:
        ...
    
    def to_numpy(self): # -> ndarray[tuple[int], dtype[floating[_32Bit]]]:
        ...
    
    def to_text(self): # -> str:
        ...
    
    def to_binary(self): # -> bytes:
        ...
    
    @classmethod
    def from_text(cls, value): # -> Self:
        ...
    
    @classmethod
    def from_binary(cls, value): # -> Self:
        ...
    


