"""
This type stub file was generated by pyright.
"""

from sqlalchemy.types import UserDefinedType

class BIT(UserDefinedType):
    cache_ok = ...
    def __init__(self, length=...) -> None:
        ...
    
    def get_col_spec(self, **kw): # -> Literal['BIT']:
        ...
    
    def bind_processor(self, dialect): # -> Callable[..., Any] | _BindProcessorType[Any] | None:
        ...
    
    class comparator_factory(UserDefinedType.Comparator):
        def hamming_distance(self, other): # -> Operators:
            ...
        
        def jaccard_distance(self, other): # -> Operators:
            ...
        
    
    


