"""
This type stub file was generated by pyright.
"""

from sqlalchemy.sql.functions import ReturnTypeFromArgs

class avg(ReturnTypeFromArgs):
    inherit_cache = ...
    package = ...


__all__ = ['avg', 'sum']
