"""
This type stub file was generated by pyright.
"""

from sqlalchemy.types import UserDefinedType

class SPARSEVEC(UserDefinedType):
    cache_ok = ...
    _string = ...
    def __init__(self, dim=...) -> None:
        ...
    
    def get_col_spec(self, **kw): # -> Literal['SPARSEVEC']:
        ...
    
    def bind_processor(self, dialect): # -> Callable[..., Any | str]:
        ...
    
    def literal_processor(self, dialect): # -> Callable[..., str]:
        ...
    
    def result_processor(self, dialect, coltype): # -> Callable[..., Any | SparseVector]:
        ...
    
    class comparator_factory(UserDefinedType.Comparator):
        def l2_distance(self, other): # -> Operators:
            ...
        
        def max_inner_product(self, other): # -> Operators:
            ...
        
        def cosine_distance(self, other): # -> Operators:
            ...
        
        def l1_distance(self, other): # -> Operators:
            ...
        
    
    


